# .coderabbit.yaml
# CodeRabbit Configuration for Sandbox Security Review
tone_instructions: |
  Use clear, professional language focused on security and safety.
  Highlight critical issues with appropriate emphasis.
  Provide actionable feedback with specific examples.

reviews:
  profile: assertive
  request_changes: auto
  high_level_summary: true
  review_status: true
  poem: false
  collapse_walkthrough: false
  

path_instructions:
  - path: "apps/api/src/sandbox/managers/sandbox.manager.ts"
    instructions: |
      CRITICAL: Review this file and ensure that:
         - Only non-negative values (>= 0) for autoDeleteInterval trigger auto-delete
         - Only stopped sandboxes are considered for auto-delete
         - Time calculations are corrected for determining if auto-delete should be triggered
         - Negative values for autoDeleteInterval disable auto-delete functionality
         - Only positive values (> 0) for autoStopInterval trigger auto-stop
         - Only started sandboxes are considered for auto-stop
         - Time calculations are corrected for determining if auto-stop should be triggered
         - 0 for autoStopInterval disables auto-stop functionality
         - A sandbox is deleted instead of stopped during auto-stop check when autoDeleteInterval is equal to 0
         - Only non-negative values (>= 0) for autoArchiveInterval trigger auto-archive
         - Only stopped sandboxes are considered for auto-archive
         - Time calculations are corrected for determining if auto-archive should be triggered
         - Negative values for autoArchiveInterval disable auto-archive functionality
         - Most importantly, ensure that the auto-delete functionality is not enabled by default and that the user must explicitly set the auto-delete interval to a non-negative value to enable it.

  - path: "apps/api/src/sandbox/services/sandbox.service.ts"
    instructions: |
      CRITICAL: Review this file and ensure that:      
         - Negative values for autoStopInterval are rejected
         - Negative values for autoStopInterval are rejected
         - Maximum interval is used when 0 is provided as user input
         - Maximum interval is used when user input is larger than the maximum interval
         - When stopping a sandbox, immediately delete it if autoDeleteInterval is 0

  - path: "apps/api/src/sandbox/entities/sandbox.entity.ts"
    instructions: |
      CRITICAL: Review this file and ensure that:      
         - Negative value for autoDeleteInterval is used as default
         - Value for lastActivityAt is updated when changes are made to the sandbox

ignore:
  - "**/*.md"
  - "**/*.json"
  - "**/test/**"
  - "**/tests/**"
  - "**/*.spec.ts"
  - "**/*.test.ts"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/.git/**"
  - "**/*.log"

chat:
  auto_reply: true