tone_instructions: |
  Adopt a concise, matter-of-fact style that gets straight to the point without unnecessary pleasantries.

reviews:
  profile: assertive
  high_level_summary: true
  high_level_summary_in_walkthrough: true
  poem: false
  collapse_walkthrough: false
  path_filters:
    - "!**/*.md"
    - "!**/*.json"
    - "!**/node_modules/**"
    - "!**/dist/**"
    - "!**/build/**"

path_instructions:
  - path: "apps/api/src/sandbox/managers/sandbox.manager.ts"
    instructions: |
      - During the auto-delete cron job, only sandboxes with non-negative values (>= 0) "autoDeleteInterval" value should be considered for deletion
      - During the auto-delete cron job, only sandboxes with "Stopped" state should be considered for deletion
      - During the auto-stop cron job, only sandboxes with "autoStopInterval" value greater than 0 should be considered for stopping
      - During the auto-stop cron job, only sandboxes with "Started" state should be considered for stopping
      - During the auto-stop cron job, if "autoDeleteInterval" is equal to 0, the sandbox should be deleted instead of stopped
      - During the auto-archive cron job, only sandboxes with "Stopped" state should be considered for archiving

  - path: "apps/api/src/sandbox/services/sandbox.service.ts"
    instructions: |
      - When creating a sandbox, negative value for "autoStopInterval" must be rejected
      - When creating a sandbox, negative value for "autoArchiveInterval" must be rejected
      - When creating a sandbox, the maximum auto-archive interval defined in app config must be used when 0 is provided as user input
      - When creating a sandbox, the maximum auto-archive interval defined in app config must be used when user input is larger than the maximum interval
      - When setting a new value for "autoStopInterval", the value must be validated and rejected if it is negative
      - When setting a new value for "autoArchiveInterval", the value must be validated and rejected if it is negative
      - When setting a new value for "autoArchiveInterval", the maximum auto-archive interval defined in app config must be used when 0 is provided as user input
      - When setting a new value for "autoArchiveInterval", the maximum auto-archive interval defined in app config must be used when user input is larger than the maximum interval
      - When stopping a sandbox, the desired state must be set to "Stopped", unless "autoDeleteInterval" is equal to 0, in which case the desired state must be set to "Destroyed"

  - path: "apps/api/src/sandbox/entities/sandbox.entity.ts"
    instructions: | 
      - The default value for "autoDeleteInterval" must be a negative value